---

- hosts: all

  tasks:
    - name: copy script
      copy:
        src: ./get-installed-pkgs.py
        dest: ./get-installed-pkgs.py 
    - name : get-pkgs
      command: python3 ./get-installed-pkgs.py


# TODO update pip - make a requirements.txt - install packages 